apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  POSTGRES_PASSWORD: bXlwYXNzd29yZGJvYg==
  POSTGRES_USER: Ym9ic3Fs

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
  labels:
    app: postgresql-db
data:
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_DB: creometry-billing
  TZ: 'UTC+1'
  PGTZ: 'UTC+1'
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
      - name: postgresql-db
        image: postgres:13-alpine
        ports:
          - containerPort: 5432
      # Configuration from ConfigMap and Secret
        envFrom:
        - secretRef:
            name: postgresql-secret
        - configMapRef:
            name: postgresql-configmap
  # Volume Claim
  volumeClaimTemplates:
  - metadata:
      name: postgresql-db-disk
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
---    
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresql-db      