# PostgreSQL StatefulSet ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
  labels:
    app: postgresql-db
data:
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_DB: creometry-billing
  TZ: 'UTC+1'
  PGTZ: 'UTC+1'