apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-api-configmap
data:
  APP_ENV: development
  Rancher_API_Url: https://localhost
  RancherBearerToken: rancher-bearer-token
  Postgresqlhost: postgresql-service.default.svc.cluster.local
  Postgresqlport: "5432"

