name: billing-api-ci

on: [push]
    
           
jobs: 

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.BILLING_API_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: creometry/billing:v0.0.1
          cache-from: type=registry,ref=${{ secrets.USERNAME }}/billing:buildcache
          cache-to: type=registry,ref=${{ secrets.BILLING_API_SECRET }}/billing:buildcache,mode=max